### ISSUE TITLE
Support Raspberry Pi 2

### ISSUE THREAD

**Issue by probonopd** [gamaral/rpi-buildroot#29]
It would be nice if we could have an optimized build that takes full advantage of the new CPU in the Raspberry Pi 2.

**Comment by ccrisan** [comment]
That's what I have in mind. As a matter of fact I'm working right now on the new version. My plans are that it works well on RaspberryPI, RaspberryPI 2 and BananaPI.

**Comment by probonopd** [comment]
Excellent, looking forward to it.

**Comment by gamaral** [comment]
@probonopd is this related to rpi-buildroot? If so, then yes. I'm working on it. :)

**Comment by probonopd** [comment]
Indeed I was talking about rpi-buildroot. But interesting to see this commit for motionPie, https://github.com/ccrisan/motionPie/commit/0d16283d50b104ef1ed43118f9dc5da025a8c601

**Comment by andor-pierdelacabeza** [comment]
I'd love that. I have several RPi 2 I'd be happy to use for testing.

I can't code but I can test and document :laughing: :ok_hand:

**Comment by gamaral** [comment]
It's on it's way. I'm almost done combining with the upstream project. :) It's just gonna take some time since I have a really bad internet connection ATM.

**Comment by gamaral** [comment]
defconfig script for RPi2 tested and added test-drive image for it.

**Comment by probonopd** [comment]
Thank you.

**Comment by andor-pierdelacabeza** [comment]
Tested  and working! During the will I'll push the limits of it a bit and see how it behaves :D :+1:
