### ISSUE TITLE
Push rpi-buildroot improvements into upstream buildroot

### ISSUE THREAD

**Issue by probonopd** [gamaral/rpi-buildroot#30]
Would it be possible to push the rpi-buildroot improvements into the upstream buildroot project, so that we can participate automatically from all improvements done there?

**Comment by gamaral** [comment]
I originally did try to upstream my changes but I had a bit of a hard time doing so and lost interest.

I have noticed though that the RPi upstream is now pretty useful. I'm considering rebaseing and using as much as I can from upstream as possible.

**Comment by andor-pierdelacabeza** [comment]
:+1:

**Comment by gamaral** [comment]
Alright, merged and tested. :) rpi-buildroot now follows upstream more closely. Test-drive image for RPi2 added.

**Comment by probonopd** [comment]
Great, thanks!
