### ISSUE TITLE
mkimage doesnt work with losetup from mint 17.1

### ISSUE THREAD

**Issue by lilphil** [gamaral/rpi-buildroot#37]
mkimage has an unrecognised option in util-linux version 2.20.1-5.1ubuntu20.4

```
/sbin/losetup: invalid option -- 'P'
```

**Comment by jasperla** [comment]
The folks of `debian-pi` fixed it like this: https://github.com/debian-pi/raspbian-ua-netinst/pull/25

**Comment by gamaral** [comment]
Issue based on older repo
