### ISSUE TITLE
BR2_PACKAGE_ALSA_UTILS_ALSAMIXER wchar dependency

### ISSUE THREAD

**Issue by lilphil** [gamaral/rpi-buildroot#38]
Ok, this could be an upstream issue too?

when these are set:
`BR2_TOOLCHAIN_BUILDROOT_WCHAR=y`
`BR2_USE_WCHAR=y`

This:
`BR2_PACKAGE_ALSA_UTILS_ALSAMIXER`

Requires this:
`BR2_PACKAGE_NCURSES_WCHAR`

**Comment by gamaral** [comment]
Retest with latest tag and reopen if needed. ;)
