### ISSUE TITLE
Test Drive Build - No Input from keyboard.

### ISSUE THREAD

**Issue by iamjoshlee** [gamaral/rpi-buildroot#40]
This could just be me missing something incredibly obvious. However, I've loaded the test drive build on to my sd card and everything boots as it should. However, if I connect a usb keyboard and boot, after reaching the login prompt, it detects that there's a new usb input, etc. Yet, it doesn't register any input from the keyboard, nor does it ever return to prompt.

**Comment by gamaral** [comment]
Ah yes. It's missing event input support. It was meant to be interacted
through the UART. :)

On Sun, Aug 30, 2015 at 1:07 PM, Josh Lee <notifications@github.com> wrote:

> This could just be me missing something incredibly obvious. However, I've
> loaded the test drive build on to my sd card and everything boots as it
> should. However, if I connect a usb keyboard and boot, after reaching the
> login prompt, it detects that there's a new usb input, etc. Yet, it doesn't
> register any input from the keyboard, nor does it ever return to prompt.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gamaral/rpi-buildroot/issues/40>.
>



-- 
gamaral
http://about.me/gamaral

**Comment by iamjoshlee** [comment]
ah got it!

**Comment by kimmobrunfeldt** [comment]
I also noticed this problem. I tried to do a new manual build where I enabled bunch of configurations, such as `input-event-daemon` and `input-tools` but I couldn't figure out which configuration I actually need to enable for USB keyboard support. Do you know which ones need to be enabled or is this something out of buildroot's scope.

**Comment by kimmobrunfeldt** [comment]
I got this fixed by changing my keyboard to another.
