### ISSUE TITLE
Failed to open vchiq instance. Raspistill

### ISSUE THREAD

**Issue by HLK21** [gamaral/rpi-buildroot#41]
I get this error by starting raspistill.
             Failed to open vchiq instance

* Fixed by changing rpi userland and rpi firmware to latest commit.

**Comment by akaer** [comment]
Same for me

**Comment by gamaral** [comment]
I'll give it a try Tonight. You guys selected the _x firmware right?

**Comment by HLK21** [comment]
Selected packages:

Target packages/Audio and video applications/ffmpeg
Target packages/Hardware handling/rpi-userland
Target packages/Hardware handling/Firmware/rpi-firmware/Firmware to boot/extended
Target packages/Libraries/Graphics/jpeg support
Target packages/Libraries/Hardware handling/lib4vl
Target packages/Networking applications/wireless tools
Target packages/Networking applications/wpa_supplicant
Target packages/Networking applications/wpa_supplicant/Enable EAP
Target packages/Networking applications/wpa_supplicant/Enable syslog support
Target packages/Networking applications/wpa_supplicant/Install wpa_cli binary
Target packages/Networking applications/wpa_supplicant/Install wpa_passphrase binary

**Comment by akaer** [comment]
I'm using the standard Raspberry Pi B (not B+). Parts from my custom defconfig can be found here https://gist.github.com/akaer/4a96308c3a652720b08b

**Comment by HLK21** [comment]
I am using raspberrypi2_defconfig

**Comment by jolyboy** [comment]
I had this problem also. Included x firmware but no luck. Then I went back to 4.0.y firmware and it worked.

**Comment by gamaral** [comment]
Okay, bumped rpi-firmware and rpi-userspace to master, I must have messed up a merge at some point. I tested it Today on the RPI A/B and RPI 2, worked a treat. :)
