### ISSUE TITLE
vc API error while loading shared libraries: libilclient.so

### ISSUE THREAD

**Issue by lecheel** [gamaral/rpi-buildroot#42]
hi,
After select rpi-userland and hello_pi examples
what should I do for following error
![vcapi](https://cloud.githubusercontent.com/assets/148137/10237279/27dab00c-68e2-11e5-922f-2129ebb7606d.png)

Thanks 
Lechee

**Comment by gamaral** [comment]
I think this was caused rpi-userland, it's been updated since. Feel free to reopen if it crops up again.

**Comment by schenkmi** [comment]
I have the same issue and I guess there is a typo in rpi-userland.mk which installs libilclient.so to libilcient.so. So the linker will never find it on the target

Correct:
define RPI_USERLAND_EXTRA_LIBS_TARGET
	$(INSTALL) -m 0644 -D \
		$(@D)/build/lib/libilclient.so \
		$(TARGET_DIR)/usr/lib/libilclient.so
endef

Cheers

Michael
