### ISSUE TITLE
/run shoud be mounted as tmpfs

### ISSUE THREAD

**Issue by polaco1782** [gamaral/rpi-buildroot#43]
Hi!

Great work on this buildroot! Thanks a lot!

Here, a quick fix on fstab, /run shoud be mounted as a tmpfs. I got nasty startup problems when my raspberry was hard powered off by a electrical surge. Many pids and ifstate files remains there, so network wont startup, and also some daemons, like minidlna

A quick fix on fstab:

tmpfs           /run           tmpfs    mode=755         0      0

Thanks!

**Comment by gamaral** [comment]
Fixed! Thanks for the report. :)
