### ISSUE TITLE
Not Booting

### ISSUE THREAD

**Issue by pramodkasbekar** [gamaral/rpi-buildroot#48]
Hi there,
I have followed same procedure what you have given in README.md manual method). After connecting my rpi to PC in minicom showing
******Uncompressing Linux... done, booting the kernel.*******
after this it, I am not getting any response from rpi.
What should be the problem? Please suggest me!!!
Thank You.

Regards,
Pramod Kasbekar
Bangalore,India

**Comment by gamaral** [comment]
Pushed a new update. Care to give it a try again?
