### ISSUE TITLE
Raspberry pi zero

### ISSUE THREAD

**Issue by Gatux** [gamaral/rpi-buildroot#49]
Hi,

Thanks a lot for your work :)
I tried the images on my raspberry pi zero, however I coundn't make it work.
Did you tried or do you have any idea how it could work ?

Thanks

**Comment by gamaral** [comment]
I don't have one, so I can't test it. :( Sorry.

**Comment by YoungCereal** [comment]
Hi for the Raspberry Zero you only need to update the firmware files in the boot Partition.

**Comment by Gatux** [comment]
Hi
I cloned the project and built it  with default config (raspberrypi_defconfig) but it would'nt work first try : keyboard works but could not do anything more.
However, using your sdimage and with what YoungCereal mentioned, I managed to make it work by changing these only two files in the boot partition : bootcode.bin and start.elf
I will continue to play with this when I have more time. Thanks.

**Comment by gamaral** [comment]
If you cloned the project and built the raspberrypi_defconfig, you shouldn't need to update the boot files, they should be updated by default.

The defconfigs I supply use the UART as the default tty. You may need to nuke the cmdline.txt file in the boot partition.

I pushed an update that will ignore the cmdline.txt in the future. :)

**Comment by Gatux** [comment]
Ok this may be why I couldnt do anything ^^
I'll try again this weekend.
By the way, is it possible to have the config you used for your images ? (ex: http://dl.guillermoamaral.com/rpi/sdcard.img.xz)

**Comment by Gatux** [comment]
Tried again today, I still had to change “TTY port” from "ttyAMA0" to "tty1" in order to have direct shell, but it works :) Thanks ^^
I can now play with it and create the perfect image for my needs :)

**Comment by gamaral** [comment]
That's what I meant by it being configured to use UART as the default console. Glad you're sorted. :)
