### ISSUE TITLE
output/images/rootfs.tar not found

### ISSUE THREAD

**Issue by bphermansson** [gamaral/rpi-buildroot#51]
Tried to use the mksdcard script but it fails: "Didn't find rpi-firmware and/or rootfs.tar! ABORT."
Then tried the manual instructions which also fails:

sudo tar -xvpsf output/images/rootfs.tar -C /media/rootfs
tar: output/images/rootfs.tar: Funktion "open" misslyckades: Filen eller katalogen finns inte
tar: Error is not recoverable: exiting now

And for sure there's no file "rootfs.tar". What's wrong?

**Comment by qnl3** [comment]
You have to configure you build to output a tar image. 
using "make nconfig"
select "Filesystem Images"
check "tar the root filesystem"
rebuild.
This should produce the tar file the script uses which is the file used in the manual instructions.

**Comment by bphermansson** [comment]
Ok thanks, that works. Now I just have to find out how to get a command prompt at the Pi.

**Comment by gamaral** [comment]
Switch the main console from the UART to TTY :)

**Comment by gamaral** [comment]
Also, if you checked out the latest tag, an image should be created for you automatically. :)

**Comment by bphermansson** [comment]
Nice! I set the TTY to "tty1" and got a login prompt. All good.
