### ISSUE TITLE
[RPI B-Plus] Wrong Terminal definition

### ISSUE THREAD

**Issue by LipkeGu** [gamaral/rpi-buildroot#55]
https://github.com/gamaral/rpi-buildroot/blob/rpi/configs/raspberrypi_defconfig#L9
@gamaral  can youchange this to "tty0" on B+ ?

* Buildroot is using tty0 and recalbox-buildroot uses also tty0
 
Otherwise we cant get a interactive shell on RPI 1 B+ :(

**Comment by LipkeGu** [comment]
#56

**Comment by gamaral** [comment]
It's not a mistake; By default I set TTY on TTL on embedded systems, that way you can talk to it without interfering with the video output.
Anyway, it's easy enough to change the TTY while configuring for your specific use case. :)
