### ISSUE TITLE
Boot Time

### ISSUE THREAD

**Issue by juandesanchezm** [gamaral/rpi-buildroot#61]
When I test sdcard2.img.xz in my raspberry pi, it's boot in 2 or 3 seconds, but when i build a new image using rpi-buildroot, the time boot is 7or 8 seconds. 

What is the difference between Test Drive and Building?

Thank you.

**Comment by MrAda** [comment]
Do you have a RPi2 or RPi3?  I suspect he customized a lot to get the times down.  I have not been successful using the sdcard2.img.xz in my RPi3.  Probably because I am using the official touchscreen/LCD.  I don't have an HDMI compatible monitor.

**Comment by gamaral** [comment]
@reysintrono If you changed nothing in the configuration. You'll need to trim down the kernel and busybox.

**Comment by MrAda** [comment]
I am going to try and build rpi myself.  I see @gamaral responded.  What items did you pare down?  Can you offer some assistance on what to do?

**Comment by gamaral** [comment]
@MrAda Yeah, it can just be that it's for the RPi2. I also don't think I've updated it since the display support was added.

**Comment by gamaral** [comment]
Pretty much removed anything that's not required by the system. Few modules, drivers that are required by the RPi build into the kernel and everything else to off.

**Comment by MrAda** [comment]
@gamaral I was thinking of trying to connect to my TV.  I think I can display my Pi's output to the TV.  I'll just have to disconnect the LCD cable for the time being.  If I knew where to find the driver for that device I'd work to get it added to build root.  So trimming down the kernel and busybox is a straight forward attempt (looking at readmes and such)?  Or will it require a surgeon? :-)

**Comment by gamaral** [comment]
Anyway, you'll need to play with it. :-) The default build should be pretty fast 7 secs for an RPi1 from cold start for example. That said, Unfortunately I really can't offer much support since I really have very little free time. :disappointed:

**Comment by MrAda** [comment]
Ok.   I will do my best.

**Comment by gamaral** [comment]
If it's the official display, I take it you only need to update the kernel and the boot files.

**Comment by MrAda** [comment]
That is correct, I do have the official 7" display

**Comment by gamaral** [comment]
Issue based on older repo
