### ISSUE TITLE
YouTube tutorial? 

### ISSUE THREAD

**Issue by qopsinonstudios** [gamaral/rpi-buildroot#66]
Hi, I am really interested on your project, I want to build my own system for my car, but I am a noob with this. I want to know if you might create a tutorial on YouTube about How to build this buildroot, if it is possible. 

Thanks in advance!

**Comment by gamaral** [comment]
I had made one before, but it was way too long -- I need to record one that's simpler to follow. Maybe in April. :-)

**Comment by qopsinonstudios** [comment]
Thank you so much! :)
