### ISSUE TITLE
Building on a Zero

### ISSUE THREAD

**Issue by moosepr** [gamaral/rpi-buildroot#69]
Hi There

I am trying to reproduce your PicoPi os for my TinyPi project 
https://hackaday.io/project/21553-pi0cket-tiny

been trying to get the base pi system to compile before i thin start trying to add options and such. Currently using a Pi0 for the compilation. i know it will take forever, but i can just leave it running until it is done, no real rush

I am getting errors when building and im just checking that it is not actually because im using a Pi0?

**Comment by gamaral** [comment]
Buildroot is pretty much meant to be used to cross-compile, so you would need a Linux system (VM should work) and build FOR the RP0.

That said, here's the repo for TinyPi: https://github.com/gamaral/rpi-buildroot/tree/tinypi ;-)
