### ISSUE TITLE
ALSA issues

### ISSUE THREAD

**Issue by johschmitz** [gamaral/rpi-buildroot#73]
I am trying to build an image with MPD based on this.
However when running MPD it complains that it can not find a soundcard:

> Jan 01 00:01 : output: Attempting to detect a alsa audio device
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4554:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4554:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4554:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5033:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM default
Jan 01 00:01 : alsa_output: Error opening default ALSA device: No such file or directory
Jan 01 00:01 : exception: Unable to detect an audio device

Any idea how to solve this?

**Comment by gamaral** [comment]
Issues are not meant to be used as a support line. That said, I'll give you a little hint: "raspberry pi audio dt parameter" ;-)
